# Generated by Django 5.1.12 on 2025-12-07 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expensa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_referencia', models.CharField(max_length=7)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cuota_basica', models.DecimalField(decimal_places=2, max_digits=10)),
                ('multas', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('reservas', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('otros', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha_emision', models.DateField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateField()),
                ('pagada', models.BooleanField(default=False)),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.propietario')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pago', models.CharField(choices=[('tarjeta', 'Tarjeta de Crédito/Débito'), ('transferencia', 'Transferencia Bancaria'), ('efectivo', 'Efectivo')], max_length=20)),
                ('referencia', models.CharField(max_length=100, unique=True)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='comprobantes_pagos/')),
                ('verificado', models.BooleanField(default=False)),
                ('expensa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finanzas.expensa')),
            ],
        ),
    ]
