# Generated by Django 5.2.6 on 2025-12-08 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_alter_vehiculo_options_vehiculo_activo_vehiculo_año_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='tipo',
            field=models.CharField(blank=True, choices=[('sedan', 'Sedán'), ('suv', 'SUV'), ('pickup', 'Pickup'), ('hatchback', 'Hatchback'), ('camioneta', 'Camioneta'), ('van', 'Van'), ('coupe', 'Coupé'), ('convertible', 'Convertible'), ('minivan', 'Minivan'), ('crossover', 'Crossover')], max_length=20, null=True),
        ),
    ]
