# Generated by Django 5.1.12 on 2025-12-08 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_vehiculo_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='foto_delete_url',
            field=models.URLField(blank=True, help_text='URL para eliminar foto de ImgBB', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='mascota',
            name='foto_url',
            field=models.URLField(blank=True, help_text='URL de foto en ImgBB', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='foto_vehiculo_delete_url',
            field=models.URLField(blank=True, help_text='URL para eliminar foto de ImgBB', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='foto_vehiculo_url',
            field=models.URLField(blank=True, help_text='URL de foto en ImgBB', max_length=500, null=True),
        ),
    ]
