# Generated by Django 5.1.12 on 2025-12-08 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_mascota_foto_delete_url_mascota_foto_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propietario',
            name='meses_mora',
            field=models.IntegerField(default=0, help_text='Cantidad de meses en mora'),
        ),
        migrations.AddField(
            model_name='propietario',
            name='restringido_por_mora',
            field=models.BooleanField(default=False, help_text='Restricción de acceso por mora'),
        ),
    ]
