# Generated by Django 5.1.12 on 2025-12-08 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rol',
            name='nombre',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('PROPIETARIO', 'Propietario'), ('GUARDIA', 'Guardia de Seguridad')], max_length=50, unique=True),
        ),
    ]
