# Generated by Django 5.2.6 on 2025-12-09 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('areas_comunes', '0004_alter_areacomun_tarifa_hora_and_more'),
        ('gestion', '0005_propietario_meses_mora_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pago', models.CharField(choices=[('reserva', 'Reserva de Área'), ('expensa', 'Expensa'), ('multa', 'Multa'), ('otro', 'Otro')], default='reserva', max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('moneda', models.CharField(default='BOB', max_length=3)),
                ('payment_intent_id', models.CharField(help_text='ID del Payment Intent de Stripe', max_length=255, unique=True)),
                ('payment_method_id', models.CharField(blank=True, help_text='ID del método de pago de Stripe', max_length=255, null=True)),
                ('charge_id', models.CharField(blank=True, help_text='ID del cargo de Stripe', max_length=255, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('completado', 'Completado'), ('fallido', 'Fallido'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Información adicional del pago')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_completado', models.DateTimeField(blank=True, null=True)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='gestion.propietario')),
                ('reserva', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos', to='areas_comunes.reservaareacomun')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'db_table': 'pagos',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['propietario', '-fecha_creacion'], name='pagos_propiet_214ded_idx'), models.Index(fields=['payment_intent_id'], name='pagos_payment_d0a5a5_idx'), models.Index(fields=['estado'], name='pagos_estado_79b102_idx')],
            },
        ),
    ]
