# Generated by Django 5.1.12 on 2025-09-09 23:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaComun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('capacidad', models.IntegerField()),
                ('horario_apertura', models.TimeField()),
                ('horario_cierre', models.TimeField()),
                ('tarifa_hora', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activa', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Expensa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_referencia', models.CharField(max_length=7)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cuota_basica', models.DecimalField(decimal_places=2, max_digits=10)),
                ('multas', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('reservas', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('otros', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha_emision', models.DateField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateField()),
                ('pagada', models.BooleanField(default=False)),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Guardia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento_identidad', models.CharField(max_length=20, unique=True)),
                ('telefono', models.CharField(max_length=15)),
                ('turno', models.CharField(max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_contratacion', models.DateField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pago', models.CharField(choices=[('tarjeta', 'Tarjeta de Crédito/Débito'), ('transferencia', 'Transferencia Bancaria'), ('efectivo', 'Efectivo')], max_length=20)),
                ('referencia', models.CharField(max_length=100, unique=True)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='comprobantes_pagos/')),
                ('expensa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.expensa')),
            ],
        ),
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento_identidad', models.CharField(max_length=20, unique=True)),
                ('telefono', models.CharField(max_length=15)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('perro', 'Perro'), ('gato', 'Gato'), ('ave', 'Ave'), ('otro', 'Otro')], max_length=20)),
                ('raza', models.CharField(blank=True, max_length=50)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='mascotas/')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mascotas', to='core.propietario')),
            ],
        ),
        migrations.AddField(
            model_name='expensa',
            name='propietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.propietario'),
        ),
        migrations.CreateModel(
            name='ComunicacionGuardia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('llamada', 'Llamada'), ('chat', 'Chat'), ('asistencia', 'Solicitud de asistencia'), ('emergencia', 'Emergencia')], max_length=20)),
                ('mensaje', models.TextField()),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_atencion', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('atendida', 'Atendida')], default='pendiente', max_length=20)),
                ('respuesta', models.TextField(blank=True)),
                ('guardia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.guardia')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.propietario')),
            ],
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('incumplimiento', 'Incumplimiento de reglas'), ('mantenimiento', 'Problema de mantenimiento'), ('seguridad', 'Incidente de seguridad'), ('ruido', 'Ruido molesto'), ('limpieza', 'Problema de limpieza'), ('otro', 'Otro')], max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('ubicacion', models.CharField(max_length=100)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='reportes/')),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('resuelto', 'Resuelto'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('prioridad', models.IntegerField(default=1)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.propietario')),
            ],
        ),
        migrations.CreateModel(
            name='ReservaAreaComun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('costo_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('completada', 'Completada')], default='pendiente', max_length=20)),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True)),
                ('codigo_reserva', models.CharField(default='95AA983A966745C', max_length=15, unique=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.areacomun')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.propietario')),
            ],
        ),
        migrations.CreateModel(
            name='UnidadHabitacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10)),
                ('edificio', models.CharField(blank=True, max_length=50)),
                ('tipo', models.CharField(choices=[('casa', 'Casa'), ('departamento', 'Departamento'), ('penthouse', 'Penthouse')], max_length=20)),
                ('piso', models.IntegerField(blank=True, null=True)),
                ('caracteristicas', models.TextField(blank=True)),
                ('propietario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='unidad', to='core.propietario')),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=30)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to='core.propietario')),
            ],
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_visitante', models.CharField(max_length=100)),
                ('documento_identidad', models.CharField(max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=15)),
                ('fecha_visita', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('placa_vehiculo', models.CharField(blank=True, max_length=10)),
                ('codigo_acceso', models.CharField(default='6BCC4926A6', max_length=10, unique=True)),
                ('qr_code', models.ImageField(blank=True, upload_to='qrcodes_visitas/')),
                ('estado', models.CharField(choices=[('programada', 'Programada'), ('en_progreso', 'En Progreso'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], default='programada', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas', to='core.propietario')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroVisita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_entrada', models.DateTimeField()),
                ('hora_salida', models.DateTimeField(blank=True, null=True)),
                ('guardia_registro', models.CharField(max_length=100)),
                ('observaciones', models.TextField(blank=True)),
                ('foto_entrada', models.ImageField(blank=True, null=True, upload_to='fotos_visitas/')),
                ('visita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.visita')),
            ],
        ),
    ]
