# Generated by Django 5.1.12 on 2025-09-10 04:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservaareacomun',
            name='codigo_reserva',
            field=models.CharField(default=uuid.uuid4, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='visita',
            name='codigo_acceso',
            field=models.CharField(default=uuid.uuid4, max_length=10, unique=True),
        ),
    ]
