# Generated by Django 5.1.12 on 2025-09-10 04:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_reservaareacomun_codigo_reserva_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visita',
            name='codigo_acceso',
            field=models.CharField(default=uuid.uuid4, max_length=36, unique=True),
        ),
    ]
