# Generated by Django 5.1.12 on 2025-09-10 04:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_visita_codigo_acceso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservaareacomun',
            name='codigo_reserva',
            field=models.CharField(default=uuid.uuid4, max_length=20, unique=True),
        ),
    ]
