# Generated by Django 5.1.12 on 2025-09-10 04:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_reservaareacomun_codigo_reserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservaareacomun',
            name='codigo_reserva',
            field=models.CharField(default=uuid.uuid4, max_length=50, unique=True),
        ),
    ]
