# Generated by Django 5.1.12 on 2025-12-07 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('incumplimiento', 'Incumplimiento de reglas'), ('mantenimiento', 'Problema de mantenimiento'), ('seguridad', 'Incidente de seguridad'), ('ruido', 'Ruido molesto'), ('limpieza', 'Problema de limpieza'), ('otro', 'Otro')], max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('ubicacion', models.CharField(max_length=100)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='reportes/')),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('resuelto', 'Resuelto'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('prioridad', models.IntegerField(default=1)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.propietario')),
            ],
        ),
    ]
