# Generated by Django 5.2.6 on 2025-12-09 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_propietario_meses_mora_and_more'),
        ('mantenimiento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='propietario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.propietario'),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
