# Generated by Django 5.1.12 on 2025-12-07 16:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guardia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento_identidad', models.CharField(max_length=20, unique=True)),
                ('telefono', models.CharField(max_length=15)),
                ('turno', models.CharField(max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_contratacion', models.DateField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ComunicacionGuardia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('llamada', 'Llamada'), ('chat', 'Chat'), ('asistencia', 'Solicitud de asistencia'), ('emergencia', 'Emergencia')], max_length=20)),
                ('mensaje', models.TextField()),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_atencion', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('atendida', 'Atendida')], default='pendiente', max_length=20)),
                ('respuesta', models.TextField(blank=True)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.propietario')),
                ('guardia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seguridad.guardia')),
            ],
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_visitante', models.CharField(max_length=100)),
                ('documento_identidad', models.CharField(max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=15)),
                ('fecha_visita', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('placa_vehiculo', models.CharField(blank=True, max_length=10)),
                ('codigo_acceso', models.CharField(default=uuid.uuid4, max_length=36, unique=True)),
                ('qr_code', models.ImageField(blank=True, upload_to='qrcodes_visitas/')),
                ('estado', models.CharField(choices=[('programada', 'Programada'), ('en_progreso', 'En Progreso'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], default='programada', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas', to='gestion.propietario')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroVisita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_entrada', models.DateTimeField()),
                ('hora_salida', models.DateTimeField(blank=True, null=True)),
                ('guardia_registro', models.CharField(max_length=100)),
                ('observaciones', models.TextField(blank=True)),
                ('foto_entrada', models.ImageField(blank=True, null=True, upload_to='fotos_visitas/')),
                ('visita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguridad.visita')),
            ],
        ),
    ]
