# Generated by Django 5.2.6 on 2025-12-08 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_alter_vehiculo_options_vehiculo_activo_vehiculo_año_and_more'),
        ('seguridad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlateRecognitionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(db_index=True, max_length=20)),
                ('plate_region', models.CharField(blank=True, max_length=50, null=True)),
                ('vehicle_type', models.CharField(blank=True, max_length=50, null=True)),
                ('vehicle_make', models.CharField(blank=True, max_length=50, null=True)),
                ('vehicle_model', models.CharField(blank=True, max_length=50, null=True)),
                ('vehicle_color', models.CharField(blank=True, max_length=30, null=True)),
                ('image', models.ImageField(upload_to='plate_recognition/')),
                ('confidence', models.CharField(choices=[('high', 'Alta'), ('medium', 'Media'), ('low', 'Baja')], max_length=20)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('is_registered', models.BooleanField(default=False)),
                ('tipo_acceso', models.CharField(choices=[('residente', 'Residente'), ('visita', 'Visita'), ('proveedor', 'Proveedor'), ('desconocido', 'Desconocido')], default='desconocido', max_length=20)),
                ('acceso_permitido', models.BooleanField(default=False)),
                ('acceso_automatico', models.BooleanField(default=False)),
                ('fecha_reconocimiento', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('guardia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='seguridad.guardia')),
                ('unidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.unidadhabitacional')),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconocimientos', to='gestion.vehiculo')),
                ('visita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconocimientos', to='seguridad.visita')),
            ],
            options={
                'verbose_name': 'Registro de Reconocimiento de Placa',
                'verbose_name_plural': 'Registros de Reconocimiento de Placas',
                'ordering': ['-fecha_reconocimiento'],
                'indexes': [models.Index(fields=['-fecha_reconocimiento'], name='seguridad_p_fecha_r_eebc1e_idx'), models.Index(fields=['plate_number'], name='seguridad_p_plate_n_553802_idx'), models.Index(fields=['acceso_permitido'], name='seguridad_p_acceso__d2c85e_idx')],
            },
        ),
    ]
