# Generated by Django 5.1.12 on 2025-12-08 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0002_platerecognitionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='platerecognitionlog',
            name='image_delete_url',
            field=models.URLField(blank=True, help_text='URL para eliminar imagen de ImgBB', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='platerecognitionlog',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL de imagen en ImgBB', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='registrovisita',
            name='foto_entrada_delete_url',
            field=models.URLField(blank=True, help_text='URL para eliminar foto de ImgBB', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='registrovisita',
            name='foto_entrada_url',
            field=models.URLField(blank=True, help_text='URL de foto en ImgBB', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='visita',
            name='qr_code_delete_url',
            field=models.URLField(blank=True, help_text='URL para eliminar QR de ImgBB', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='visita',
            name='qr_code_url',
            field=models.URLField(blank=True, help_text='URL de QR en ImgBB', max_length=500, null=True),
        ),
    ]
