# Generated by Django 5.1.12 on 2025-12-07 16:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaComun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('capacidad', models.IntegerField()),
                ('horario_apertura', models.TimeField()),
                ('horario_cierre', models.TimeField()),
                ('tarifa_hora', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activa', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReservaAreaComun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('costo_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('completada', 'Completada')], default='pendiente', max_length=20)),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True)),
                ('codigo_reserva', models.CharField(default=uuid.uuid4, max_length=50, unique=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='areas_comunes.areacomun')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.propietario')),
            ],
        ),
    ]
