# Generated by Django 5.2.6 on 2025-12-09 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas_comunes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservaareacomun',
            name='num_personas',
            field=models.IntegerField(default=1),
        ),
    ]
