# Generated by Django 5.2.6 on 2025-12-09 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas_comunes', '0002_reservaareacomun_num_personas'),
    ]

    operations = [
        migrations.AddField(
            model_name='areacomun',
            name='tipo_cobro',
            field=models.CharField(choices=[('por_hora', 'Por Hora'), ('pago_fijo', 'Pago Fijo')], default='por_hora', max_length=20),
        ),
        migrations.AlterField(
            model_name='areacomun',
            name='tarifa_hora',
            field=models.DecimalField(decimal_places=2, help_text='Tarifa por hora/persona o pago fijo por persona', max_digits=10),
        ),
    ]
