# Generated by Django 5.2.6 on 2025-12-09 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas_comunes', '0003_areacomun_tipo_cobro_alter_areacomun_tarifa_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areacomun',
            name='tarifa_hora',
            field=models.DecimalField(decimal_places=2, help_text='Tarifa por hora/persona, pago fijo por persona o pago único', max_digits=10),
        ),
        migrations.AlterField(
            model_name='areacomun',
            name='tipo_cobro',
            field=models.CharField(choices=[('por_hora', 'Por Hora/Persona'), ('pago_fijo', 'Pago Fijo por Persona'), ('pago_unico', 'Pago Único')], default='por_hora', max_length=20),
        ),
    ]
